### ISSUE TITLE
框架有问题，为什么一定要加上Rv才能使用，按照步骤来实现，根本实现不了

### ISSUE THREAD

**Issue by Xxj-star** [zaaach/TransformersLayout#1]

**Comment by zaaach** [comment]
直接单独使用也没问题，可以贴出你的代码吗？

**Comment by Xxj-star** [comment]
app:tl_scrollbarTrackColor="#f0f0f0"
    app:tl_scrollbarThumbColor="#ff1919" 设置色值没有反应 根本改变不了色值

**Comment by zaaach** [comment]
好的，稍后发个版本

**Comment by zaaach** [comment]
@xuxinjiang 新版1.0.1试下

**Comment by Xxj-star** [comment]
作者我可以加你QQ吗 加我一下拉我进群吧 申请加群一直没通过 478104175
