### ISSUE TITLE
开启混淆报错

### ISSUE THREAD

**Issue by GXSZone** [zaaach/TransformersLayout#13]
崩溃信息:
Binary XML file line #117 in layout/activity_mood: com.zzx.headerlayout_kotlin.transformation.ScrollTransformation

类名:null

方法:null

行数:0

**Comment by GXSZone** [comment]
-keep class com.zzx.headerlayout_kotlin.transformation.ScrollTransformation  要全都保持吗

**Comment by zaaach** [comment]
看信息并不是本库的包名

**Comment by GXSZone** [comment]
> 看信息并不是本库的包名

抱歉，看到最后的包名差不多，想起了是另一个，抱歉
