### ISSUE TITLE
滚动条宽度

### ISSUE THREAD

**Issue by gzpaiwxc** [zaaach/TransformersLayout#15]
大佬, 希望加一个可以设置滚动条宽度的方法, 就是不让黄色滚动条按比例变长变短, 能够设置固定宽度, 即使金刚区列表变多变少, 滚动条宽度也不会改变

**Comment by zaaach** [comment]
@gzpaiwxc 功能已实现，这两天会更新一次版本

**Comment by zaaach** [comment]
@gzpaiwxc v1.0.8版本已更新
