### ISSUE TITLE
2行 怎么横行排列

### ISSUE THREAD

**Issue by yuanchenghao** [zaaach/TransformersLayout#7]
0 2 4 6 8           0 1 2 3 4
 1 3 5 7 9   变成  5 6 7 8 9

**Comment by zaaach** [comment]
之前考虑过这个问题，抽时间试着实现一下

**Comment by yuanchenghao** [comment]
试着修改了一下 没实现 现在是修改了一下数据

**Comment by zaaach** [comment]
@yuanchenghao 1.0.3版本增加了数据排序功能
