### ISSUE TITLE
有些情况下控件宽度都为0

### ISSUE THREAD

**Issue by hexu2016** [zaaach/TransformersLayout#9]
//每个item平分整个屏幕的宽度
        RecyclerView.LayoutParams params = (RecyclerView.LayoutParams) itemView.getLayoutParams();
        params.width = mRecyclerView.getMeasuredWidth() / spanCount;
我的情况是这里获取到的MeasuredWidth和width都为0..延时加载后,MeasuredWidth为0.width正确了,但是在onBind里面读取控件的宽高都为0,什么情况?

**Comment by zaaach** [comment]
@hexu2016  最新版1.0.7已修复
